spring.application.name=LudiBox
spring.profiles.active=test

jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub


#DataSource Local com MySQL - Caleb
#spring.datasource.url=jdbc:mysql://localhost:3306/ludibox?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=2004
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DataSource MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ludibox?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Opcional, caso esteja usando JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Configurações de E-mail LudiBox - Gmail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ludiboxnaoresponda@gmail.com
spring.mail.password=eifp qzcc htnv sank
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.transport.protocol=smtp

